// Shared product data. product.html is the reusable PDP template — it reads
// ?id=<slug> and renders whichever product matches.
const PRODUCTS = [
  {
    slug: 'smart-watch-pro',
    name: 'Smart Watch Pro',
    brand: 'Pulse',
    price: 129.99,
    oldPrice: 159.99,
    size: '44mm',
    category: 'Electronics',
    rating: 4.6,
    reviews: 128,
    lead: 'Track workouts, heart rate, and daily activity without reaching for your phone — seven-day battery, always-on display.',
    targets: 'Heart Rate, SpO2, GPS, Sleep Tracking',
    suited: 'Everyday Fitness & Notifications',
    format: 'Aluminum Case, Silicone Band',
    ingredients: 'Watch, Magnetic Charging Puck, Quick Start Guide',
    images: ['assets/images/hero-smartwatch.jpg', 'assets/images/product-smartwatch-2.jpg', 'assets/images/product-smartwatch.jpg'],
    alt: 'Smartwatch with black display, angled product shot'
  },
  {
    slug: 'wireless-headphones',
    name: 'Wireless Headphones',
    brand: 'Wavecore',
    price: 89.99,
    oldPrice: 119.99,
    size: 'Over-Ear',
    category: 'Electronics',
    rating: 4.5,
    reviews: 96,
    lead: 'Active noise cancellation and a 30-hour battery in a fold-flat design built for daily commutes and long flights.',
    targets: 'Active Noise Cancellation, 30-Hr Battery',
    suited: 'Commuting & Travel',
    format: 'Over-Ear, Bluetooth 5.3',
    ingredients: 'Headphones, USB-C Cable, Carry Case',
    images: ['assets/images/product-headphones-2.jpg', 'assets/images/product-headphones-3.jpg', 'assets/images/product-headphones.jpg'],
    alt: 'Premium wireless over-ear headphones product photo'
  },
  {
    slug: 'leather-backpack',
    name: 'Leather Backpack',
    brand: 'Northfield',
    price: 59.99,
    oldPrice: 79.99,
    size: 'One Size',
    category: 'Fashion',
    rating: 4.5,
    reviews: 74,
    lead: 'A padded 15" laptop sleeve, water-resistant canvas, and enough pockets to carry a full day of essentials.',
    targets: 'Padded 15" Laptop Sleeve, Water-Resistant',
    suited: 'Work, Travel & Everyday Carry',
    format: 'Waxed Canvas & Leather Trim',
    ingredients: 'Backpack, Rain Cover, Care Card',
    images: ['assets/images/product-backpack-2.jpg', 'assets/images/product-backpack.jpg', 'assets/images/product-backpack-3.jpg'],
    alt: 'Leather-trimmed backpack product photo'
  },
  {
    slug: 'running-shoes',
    name: 'Running Shoes',
    brand: 'Stride',
    price: 66.99,
    oldPrice: 89.99,
    size: 'US 5–12',
    category: 'Sports',
    rating: 4.6,
    reviews: 63,
    lead: "Responsive cushioning and a breathable knit upper built to keep pace whether you're on the road or the treadmill.",
    targets: 'Responsive Cushioning, Breathable Knit',
    suited: 'Running & Daily Training',
    format: 'Rubber Outsole, True to Size',
    ingredients: 'Shoes, Extra Laces, Shoe Bag',
    images: ['assets/images/product-shoes.jpg', 'assets/images/product-shoes-2.jpg', 'assets/images/product-shoes-3.jpg'],
    alt: 'Running shoe product photo'
  },
  {
    slug: 'smartphone-128gb',
    name: 'Smartphone 128GB',
    brand: 'Nova',
    price: 699.99,
    oldPrice: 899.99,
    size: '128GB',
    category: 'Electronics',
    rating: 4.8,
    reviews: 112,
    lead: 'A 128GB flagship with all-day battery life and a pro-grade camera system, ready for whatever the day brings.',
    targets: 'Pro Camera System, All-Day Battery',
    suited: 'Everyday Use & Photography',
    format: '128GB Storage, 6.5" Display',
    ingredients: 'Phone, USB-C Cable, SIM Tool',
    images: ['assets/images/product-smartphone-2.jpg', 'assets/images/product-smartphone-3.jpg', 'assets/images/product-smartphone.jpg'],
    alt: 'Smartphone on stand product photo'
  },
  {
    slug: 'sunglasses-uv400',
    name: 'Sunglasses UV400',
    brand: 'Solstice',
    price: 19.99,
    oldPrice: 39.99,
    size: 'One Size',
    category: 'Fashion',
    rating: 4.4,
    reviews: 88,
    lead: 'Polarized UV400 lenses in a lightweight frame that looks as good on a hike as it does at the beach.',
    targets: 'Polarized, UV400 Protection',
    suited: 'Everyday Outdoor Wear',
    format: 'Acetate Frame, Polarized Lenses',
    ingredients: 'Sunglasses, Microfiber Pouch',
    images: ['assets/images/product-sunglasses-3.jpg', 'assets/images/product-sunglasses-2.jpg', 'assets/images/product-sunglasses.jpg'],
    alt: 'Sunglasses product photo'
  },
  {
    slug: 'accent-chair',
    name: 'Modern Accent Chair',
    brand: 'Loomis',
    price: 189.99,
    oldPrice: 249.99,
    size: 'One Size',
    category: 'Home & Living',
    rating: 4.7,
    reviews: 54,
    lead: 'A curved, plush-upholstered accent chair that adds a soft, sculptural touch to any reading nook or living room corner.',
    targets: 'Sculptural Curved Frame, Plush Upholstery',
    suited: 'Living Rooms & Reading Nooks',
    format: 'Fabric Upholstery, Metal or Wood Legs',
    ingredients: 'Chair, Assembly Tools, Care Guide',
    images: ['assets/images/chair-2.jpg', 'assets/images/category-home-living.jpg', 'assets/images/chair-3.jpg'],
    alt: 'Modern upholstered accent chair product photo'
  },
  {
    slug: 'everyday-makeup-set',
    name: 'Everyday Makeup Set',
    brand: 'Verrà',
    price: 34.99,
    oldPrice: 49.99,
    size: '3-Piece Set',
    category: 'Beauty',
    rating: 4.5,
    reviews: 102,
    lead: 'A foundation, concealer, and pressed powder trio built for a fast, natural everyday base.',
    targets: 'Buildable Coverage, Lightweight Finish',
    suited: 'Normal to Combination Skin',
    format: 'Liquid Foundation, Concealer, Pressed Powder',
    ingredients: 'Foundation, Concealer, Powder Compact',
    images: ['assets/images/makeup-2.jpg', 'assets/images/category-beauty.jpg', 'assets/images/makeup-3.jpg'],
    alt: 'Makeup set product photo'
  },
  {
    slug: 'plush-teddy-bear',
    name: 'Plush Teddy Bear',
    brand: 'Cubby',
    price: 24.99,
    oldPrice: 34.99,
    size: '14 in',
    category: 'Toys & Games',
    rating: 4.8,
    reviews: 71,
    lead: 'A super-soft plush bear sized just right for gifting, cuddling, or sitting proudly on a shelf.',
    targets: 'Ultra-Soft Plush, Huggable Size',
    suited: 'Ages 3+ & Gift Giving',
    format: '14in, Polyester Plush',
    ingredients: 'Bear, Gift-Ready Packaging',
    images: ['assets/images/teddy-2.jpg', 'assets/images/category-toys.jpg', 'assets/images/teddy-3.jpg'],
    alt: 'Plush teddy bear product photo'
  }
];
